<h1>Pages</h1>

<table border="0" cellpadding="0" cellspacing="0">

<thead>
  <tr>
    <th>ID</th>
    <th>Path</th>
    <th>Layout</th>
    <th>Template</th>
    <th>Azioni</th>
  </tr>
</thead>

<tbody>
  <?php foreach($pages as $page): ?>
  <tr>
    <td><?php echo $page['id'] ?></td>
    <td><?php echo $page['title'] ?></td>
    <td><?php echo $page['decorator'] ?></td>
    <td><?php echo $page['template'] ?></td>
    <td>
      <ul>
        <li>Modifica</li>
        <li>Abilita</li>
        <li>Elimina</li>
      </ul>
    </td>
  </tr>
  <?php endforeach; ?>  
</tbody>

</table>

