<!DOCTYPE html>
<html lang="it">
<head>
  <?php echo $this->loadMeta() ?>
	<meta charset="utf-8">
  <meta name="author" content="Massimo Naccari" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

  <?php echo $this->loadStylesheet() ?>
  <?php echo $this->loadJavascript() ?>

</head>

<body>

<div class="container">

  <p>decorated with "standardLayout.view.php"</p>

  <?php echo $_content ?>

</div>

</body>
</html>
