<!DOCTYPE html>
<html>
<head>

    <title>Core duo</title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

    <?php echo $this->getAsset()->loadStylesheet() ?>
    <?php echo $this->getAsset()->loadJavascript() ?>
    <?php echo $this->getHtml()->loadMeta() ?>

</head>

<body>

    <div class="container">

        <?php $this->loadTemplate('Global/header') ?>

        <?php echo $_content ?>

        <?php $this->loadTemplate('Global/footer') ?>

    </div> <!-- /container -->


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</body>
</html>