<?php $this->decorate('Layouts/layout'); ?>


<!-- Jumbotron -->
<div class="jumbotron">
    <h1>Core Framework Refactorized!</h1>
    <p class="lead">Refactoring allegro e spensierato.</p>
    <p><a class="btn btn-lg btn-success" href="#" role="button">Richiesta Ajax</a></p>
</div>

<!-- Example row of columns -->
<div class="row">
    <div class="col-lg-4">
        <h2>MVC</h2>
        <p>Ma va? Pazzesco. Sei sicuro che sia MVC??? A me sembra che esageri</p>
        <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-lg-4">
        <h2>Symfony Components</h2>
        <p>Perché fa figo</p>
        <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-lg-4">
        <h2>PHP 5.5</h2>
        <p>Refactoring?! Inutile? No se pensi che ce l'avevo già! Ti ti xe bon far un framework? E quanti ti ghe ne ga fatti?</p>
        <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
    </div>
</div>