
<!-- Jumbotron -->
<div class="jumbotron">
    <h1>The Un-community Framework!</h1>
    <p class="lead">Develop without knowing how...because you already know how to do it!</p>
</div>

<!-- Example row of columns -->
<div class="row">
    <div class="col-lg-12">
        <h1>Free docs</h1>
        <p>It could seems weird, but you don't need it! Just open the framework wiki site you always used until yesterday: Symfony, Yii, Laravel...
        and you will be magically able to develop for Core Framework, the uncommon un-community framework</p>
        <h2>Why all this?</h2>
        <p>Because it is just the framework in the closet since far 2008, today revamped!</p>
        <h2>Reinvent the wheel...</h2>
        <p>when you are learning because you will learn a lot about why things are did in a certain way today</p>
        <h2>Refactoring</h2>
        <p>Some things changes, other things never changes!</p>
    </div>

    <div class="col-lg-4">
        <h2>MVC</h2>
        <p>It's absolutly real amazing fantastic MVC paradigm compliant!</p>
        <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-lg-4">
        <h2>Symfony Components</h2>
        <p>Because it's cool and usefull</p>
        <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-lg-4">
        <h2>PHP 5.5</h2>
        <p>Refactoring?! Inutile? No se pensi che ce l'avevo già! Ti ti xe bon far un framework? E quanti ti ghe ne ga fatti?</p>
        <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
    </div>
</div>