<div class="masthead">
    <h3 class="text-muted">Core Framework</h3>
    <ul class="nav nav-justified">
        <li class="active"><a href="<?php echo $this->context->getRouting()->get('home')->createUrl() ?>">Home</a></li>
        <li><a href="<?php echo $this->context->getRouting()->get('security_signin')->createUrl() ?>">Signin</a></li>
        <li><a href="<?php echo $this->context->getRouting()->get('static_content')->createUrl(array('_action' => 'who', 'name' => 'massimo')) ?>">Who</a></li>
        <li><a href="#">Where</a></li>
        <li><a href="#">Contact</a></li>
    </ul>
</div>